# Generated by Django 4.1.7 on 2023-03-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='file_name',
            field=models.CharField(default=1, max_length=80, verbose_name='File Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='file_path',
            field=models.CharField(default=1, max_length=200, verbose_name='FilePath'),
            preserve_default=False,
        ),
    ]
