# Generated by Django 4.1.7 on 2023-03-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='time',
            field=models.DateField(auto_now=True, verbose_name='Time'),
        ),
    ]
