# Generated by Django 4.1.7 on 2023-03-09 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_alter_uploadfile_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 9, 6, 26, 7, 952374, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
    ]
