# Generated by Django 4.1.7 on 2023-03-10 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_alter_uploadfile_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 10, 4, 52, 13, 410345, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
    ]
