# Generated by Django 4.1.7 on 2023-03-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_alter_uploadfile_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='time',
            field=models.TimeField(auto_now=True, verbose_name='Time'),
        ),
    ]
